# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GestionnairePi
                                 A QGIS plugin
 gestionnaire pi
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-15
        copyright            : (C) 2025 by xavier
        email                : Xavier.garachon@externe.grdf.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GestionnairePi class from file GestionnairePi.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #     
    from .gestionnaire_pi import GestionnairePi     
    return GestionnairePi(iface)